version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
  target-branch: main
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automated
  reviewers: []
  groups:
    actions:
      update-types:
      - patch
      - minor

- package-ecosystem: pip
  directory: /docs
  schedule:
    interval: weekly
    day: monday
  target-branch: main
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automated
  reviewers: []

- package-ecosystem: pip
  directory: /tests
  schedule:
    interval: weekly
    day: monday
    target-branch: main
    open-pull-requests-limit: 10
    labels:
    - dependencies
    - automated
    reviewers: []

- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    day: monday
  target-branch: main
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automated
  reviewers: []

- package-ecosystem: npm
  directory: /web
  schedule:
    interval: weekly
    day: monday
  target-branch: main
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automated
  reviewers: []

- package-ecosystem: gitsubmodule
  directory: /specs/proofs
  schedule:
    interval: weekly
    day: monday
  target-branch: main
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - automated
  reviewers: []
