ALL_DOCTYPE_NAMES = [
    "thesis",
    "dissertation",
    "article",
    "journal",
    "inlinepaper",
    "book",
    "manual",
    "technicalreport",
    "standard",
    "patent",
    "cv",
    "cover-letter",
    "poster",
    "presentation",
    "letter",
    "dictionary",
    "homework",
    "exam",
    "research-proposal",
    "recipe",
    "lecture-notes",
    "syllabus",
    "handout",
    "memo",
    "white-paper",
    "invoice",
]

ALL_EXAMPLE_NAMES = [
    "accessibility-test",
    "beamer-academic",
    "beamer-corporate",
    "beamer-minimal",
    "article-color",
    "article",
    "book",
    "citation-styles",
    "cjk-chinese",
    "cjk-japanese",
    "cjk-korean",
    "color-themes",
    "cover-letter-formal",
    "cover-letter",
    "cv-twopage",
    "cv",
    "dictionary",
    "dissertation",
    "exam",
    "handout",
    "homework",
    "inline-paper",
    "journal",
    "lecture-notes",
    "letter",
    "lua-showcase",
    "manual",
    "memo",
    "minimal-custom",
    "minimal-starter",
    "multi-language",
    "patent",
    "poster",
    "presentation",
    "research-proposal",
    "recipe",
    "rtl-arabic",
    "rtl-hebrew",
    "standard",
    "syllabus",
    "technical-report",
    "thesis-spacing",
    "thesis-tuhh",
    "thesis",
    "white-paper",
    "invoice",
]

DOCTYPE_TO_CLASS = {
    "thesis": "scrbook",
    "dissertation": "scrbook",
    "book": "scrbook",
    "dictionary": "scrbook",
    "article": "scrartcl",
    "journal": "scrartcl",
    "inlinepaper": "scrartcl",
    "cv": "scrartcl",
    "cover-letter": "scrartcl",
    "poster": "scrartcl",
    "presentation": "scrartcl",
    "letter": "scrartcl",
    "homework": "scrartcl",
    "exam": "scrartcl",
    "lecture-notes": "scrartcl",
    "syllabus": "scrartcl",
    "handout": "scrartcl",
    "memo": "scrartcl",
    "white-paper": "scrartcl",
    "invoice": "scrartcl",
    "recipe": "scrartcl",
    "manual": "scrreprt",
    "technicalreport": "scrreprt",
    "standard": "scrreprt",
    "patent": "scrreprt",
    "research-proposal": "scrreprt",
}

# Aliases that map example names to canonical doctypes
# (examples whose directory name differs from their doctype option)
DOCTYPE_ALIASES = {
    "technical-report": "technicalreport",
    "inline-paper": "inlinepaper",
    "cover-letter-formal": "cover-letter",
    "cv-twopage": "cv",
    "thesis-spacing": "thesis",
    "thesis-tuhh": "thesis",
    "article-color": "article",
    "citation-styles": "article",
    "multi-language": "article",
    "cjk-chinese": "article",
    "cjk-japanese": "article",
    "cjk-korean": "article",
    "rtl-arabic": "article",
    "rtl-hebrew": "article",
    "color-themes": "article",
    "lua-showcase": "article",
    "accessibility-test": "article",
    "minimal-custom": None,  # no doctype
    "minimal-starter": None,  # no doctype
}
