ALL_DOCTYPE_NAMES = [
    "thesis",
    "dissertation",
    "article",
    "journal",
    "inlinepaper",
    "book",
    "manual",
    "technicalreport",
    "standard",
    "patent",
    "cv",
    "cover-letter",
    "poster",
    "presentation",
    "letter",
    "dictionary",
    "homework",
    "exam",
    "research-proposal",
    "recipe",
    "lecture-notes",
    "syllabus",
    "handout",
    "memo",
    "white-paper",
    "invoice",
    "beamer",
    "grant-proposal",
    "ieee",
    "book-chapter",
    "lab-report",
    "literature-review",
    "thesis-proposal",
    "annotated-bibliography",
    "proceedings",
    "preprint",
    "working-paper",
    "business-letter",
    "meeting-minutes",
    "quarterly-report",
    "strategic-plan",
    "product-spec",
    "course-material",
    "course-notes",
    "textbook",
    "quiz",
    "lesson-plan",
    "software-documentation",
    "api-reference",
    "changelog",
    "technical-spec",
    "blog-post",
    "newsletter",
    "brochure",
    "invitation",
    "program",
    "legislation",
    "regulation",
    "annual-report",
    "case-study",
]

ALL_EXAMPLE_NAMES = [
    "accessibility-test",
    "advanced-article",
    "advanced-beamer",
    "advanced-bibliography",
    "advanced-math",
    "advanced-report",
    "advanced-tables",
    "advanced-thesis",
    "advanced-tikz",
    "annotated-bibliography",
    "annual-report",
    "api-reference",
    "article",
    "article-bengali",
    "article-chinese-traditional",
    "article-color",
    "article-czech",
    "article-danish",
    "article-dutch",
    "article-finnish",
    "article-french",
    "article-german-formal",
    "article-greek",
    "article-hindi",
    "article-italian",
    "article-norwegian",
    "article-polish",
    "article-portuguese",
    "article-russian",
    "article-spanish",
    "article-swedish",
    "article-thai",
    "article-turkish",
    "article-ukrainian",
    "article-vietnamese",
    "beamer-academic",
    "beamer-corporate",
    "beamer-defense",
    "beamer-minimal",
    "beamer-native",
    "bilingual-thesis",
    "blog-post",
    "book",
    "book-chapter",
    "brochure",
    "business-letter",
    "case-study",
    "changelog",
    "citation-styles",
    "cjk-chinese",
    "cjk-japanese",
    "cjk-korean",
    "color-themes",
    "course-material",
    "course-notes",
    "cover-letter",
    "cover-letter-formal",
    "cv",
    "cv-twopage",
    "dictionary",
    "dissertation",
    "exam",
    "grant-proposal",
    "handout",
    "homework",
    "ieee-paper",
    "inline-paper",
    "invitation",
    "invoice",
    "journal",
    "lab-report",
    "lecture-notes",
    "legislation",
    "lesson-plan",
    "letter",
    "literature-review",
    "lua-showcase",
    "manual",
    "meeting-minutes",
    "memo",
    "minimal-custom",
    "minimal-starter",
    "multi-language",
    "music",
    "newsletter",
    "patent",
    "plugin-demo",
    "poster",
    "preprint",
    "presentation",
    "proceedings",
    "product-spec",
    "program",
    "quarterly-report",
    "quiz",
    "recipe",
    "regulation",
    "research-proposal",
    "rtl-arabic",
    "rtl-hebrew",
    "software-documentation",
    "standard",
    "strategic-plan",
    "syllabus",
    "technical-report",
    "technical-spec",
    "textbook",
    "thesis",
    "thesis-aalto",
    "thesis-cambridge",
    "thesis-chalmers",
    "thesis-chinese",
    "thesis-cmu",
    "thesis-columbia",
    "thesis-epfl",
    "thesis-eth",
    "thesis-harvard",
    "thesis-imperial",
    "thesis-japanese",
    "thesis-kit",
    "thesis-mit",
    "thesis-ntnu",
    "thesis-oxford",
    "thesis-princeton",
    "thesis-proposal",
    "thesis-spacing",
    "thesis-stanford",
    "thesis-tudelft",
    "thesis-tuhh",
    "thesis-tum",
    "thesis-uoft",
    "thesis-yale",
    "white-paper",
    "working-paper",
]

DOCTYPE_TO_CLASS = {
    "thesis": "scrbook",
    "dissertation": "scrbook",
    "book": "scrbook",
    "dictionary": "scrbook",
    "proceedings": "scrbook",
    "textbook": "scrbook",
    "article": "scrartcl",
    "journal": "scrartcl",
    "inlinepaper": "scrartcl",
    "cv": "scrartcl",
    "cover-letter": "scrartcl",
    "poster": "scrartcl",
    "presentation": "scrartcl",
    "letter": "scrartcl",
    "homework": "scrartcl",
    "exam": "scrartcl",
    "lecture-notes": "scrartcl",
    "syllabus": "scrartcl",
    "handout": "scrartcl",
    "memo": "scrartcl",
    "white-paper": "scrartcl",
    "invoice": "scrartcl",
    "recipe": "scrartcl",
    "blog-post": "scrartcl",
    "newsletter": "scrartcl",
    "brochure": "scrartcl",
    "invitation": "scrartcl",
    "program": "scrartcl",
    "changelog": "scrartcl",
    "grant-proposal": "scrartcl",
    "ieee": "scrartcl",
    "book-chapter": "scrartcl",
    "lab-report": "scrartcl",
    "literature-review": "scrartcl",
    "annotated-bibliography": "scrartcl",
    "preprint": "scrartcl",
    "working-paper": "scrartcl",
    "business-letter": "scrartcl",
    "meeting-minutes": "scrartcl",
    "case-study": "scrartcl",
    "quiz": "scrartcl",
    "lesson-plan": "scrartcl",
    "course-notes": "scrartcl",
    "beamer": "beamer",
    "manual": "scrreprt",
    "technicalreport": "scrreprt",
    "standard": "scrreprt",
    "patent": "scrreprt",
    "research-proposal": "scrreprt",
    "thesis-proposal": "scrreprt",
    "quarterly-report": "scrreprt",
    "strategic-plan": "scrreprt",
    "product-spec": "scrreprt",
    "course-material": "scrreprt",
    "software-documentation": "scrreprt",
    "api-reference": "scrreprt",
    "technical-spec": "scrreprt",
    "legislation": "scrreprt",
    "regulation": "scrreprt",
    "annual-report": "scrreprt",
}

# Aliases that map example names to canonical doctypes
# (examples whose directory name differs from their doctype option)
DOCTYPE_ALIASES = {
    "technical-report": "technicalreport",
    "inline-paper": "inlinepaper",
    "cover-letter-formal": "cover-letter",
    "cv-twopage": "cv",
    "thesis-spacing": "thesis",
    "thesis-tuhh": "thesis",
    "article-color": "article",
    "citation-styles": "article",
    "multi-language": "article",
    "cjk-chinese": "article",
    "cjk-japanese": "article",
    "cjk-korean": "article",
    "rtl-arabic": "article",
    "rtl-hebrew": "article",
    "color-themes": "article",
    "lua-showcase": "article",
    "accessibility-test": "article",
    "minimal-custom": None,  # no doctype
    "minimal-starter": None,  # no doctype
    "beamer-academic": "presentation",
    "beamer-corporate": "presentation",
    "beamer-minimal": "presentation",
    "beamer-defense": "presentation",
    "beamer-native": "beamer",
    "article-bengali": "article",
    "article-chinese-traditional": "article",
    "article-czech": "article",
    "article-danish": "article",
    "article-dutch": "article",
    "article-finnish": "article",
    "article-french": "article",
    "article-german-formal": "article",
    "article-greek": "article",
    "article-hindi": "article",
    "article-italian": "article",
    "article-norwegian": "article",
    "article-polish": "article",
    "article-portuguese": "article",
    "article-russian": "article",
    "article-spanish": "article",
    "article-swedish": "article",
    "article-thai": "article",
    "article-turkish": "article",
    "article-ukrainian": "article",
    "article-vietnamese": "article",
    "thesis-aalto": "thesis",
    "thesis-cambridge": "thesis",
    "thesis-chalmers": "thesis",
    "thesis-chinese": "thesis",
    "thesis-cmu": "thesis",
    "thesis-columbia": "thesis",
    "thesis-epfl": "thesis",
    "thesis-eth": "thesis",
    "thesis-harvard": "thesis",
    "thesis-imperial": "thesis",
    "thesis-japanese": "thesis",
    "thesis-kit": "thesis",
    "thesis-mit": "thesis",
    "thesis-ntnu": "thesis",
    "thesis-oxford": "thesis",
    "thesis-princeton": "thesis",
    "thesis-stanford": "thesis",
    "thesis-tudelft": "thesis",
    "thesis-tum": "thesis",
    "thesis-uoft": "thesis",
    "thesis-yale": "thesis",
    # New examples with different dir names vs doctypes
    "ieee-paper": "ieee",
    "technical-spec": "technical-spec",
    # Advanced examples using existing doctypes
    "advanced-thesis": "thesis",
    "advanced-article": "article",
    "advanced-beamer": "beamer",
    "advanced-report": "technicalreport",
    "advanced-bibliography": "article",
    "advanced-math": "article",
    "advanced-tables": "article",
    "advanced-tikz": "article",
    "bilingual-thesis": "thesis",
}
