ALL_DOCTYPE_NAMES = [
    "thesis",
    "dissertation",
    "article",
    "journal",
    "inlinepaper",
    "book",
    "manual",
    "technicalreport",
    "standard",
    "patent",
    "cv",
    "cover-letter",
    "poster",
    "presentation",
    "letter",
    "dictionary",
    "homework",
    "exam",
    "research-proposal",
    "recipe",
    "lecture-notes",
    "syllabus",
    "handout",
    "memo",
    "white-paper",
    "invoice",
    "beamer",
    "grant-proposal",
    "ieee",
    "book-chapter",
    "lab-report",
    "literature-review",
    "thesis-proposal",
    "annotated-bibliography",
    "proceedings",
    "preprint",
    "working-paper",
    "business-letter",
    "meeting-minutes",
    "quarterly-report",
    "strategic-plan",
    "product-spec",
    "course-material",
    "course-notes",
    "textbook",
    "quiz",
    "lesson-plan",
    "software-documentation",
    "api-reference",
    "changelog",
    "technical-spec",
    "blog-post",
    "newsletter",
    "brochure",
    "invitation",
    "program",
    "legislation",
    "regulation",
    "annual-report",
    "case-study",
    # --- Academic / Research (expanded) ---
    "conference-paper",
    "meta-analysis",
    "research-notebook",
    "clinical-report",
    "data-sheet",
    "experiment-log",
    "survey-report",
    "review-article",
    "dissertation-proposal",
    "postdoc-report",
    # --- Business / Professional (expanded) ---
    "business-plan",
    "market-analysis",
    "financial-report",
    "employee-handbook",
    "onboarding-guide",
    "performance-review",
    "project-charter",
    "risk-assessment",
    "stakeholder-report",
    "pitch-deck",
    "press-release",
    "media-kit",
    # --- Technical / Documentation (expanded) ---
    "user-guide",
    "developer-guide",
    "operations-manual",
    "architecture-document",
    "design-document",
    "test-plan",
    "deployment-guide",
    "troubleshooting-guide",
    "coding-standards",
    "data-dictionary",
    "system-design",
    # --- Legal / Government (expanded) ---
    "contract",
    "terms-of-service",
    "privacy-policy",
    "legal-brief",
    "court-filing",
    "affidavit",
    "compliance-document",
    "policy-document",
    "public-comment",
    "impact-report",
    "audit-report",
    "feasibility-study",
    # --- Creative / Lifestyle (expanded) ---
    "novel",
    "short-story",
    "poetry-collection",
    "screenplay",
    "comic-book",
    "zine",
    "art-catalogue",
    "photo-book",
    "travel-guide",
    "greeting-card",
    "wedding-invitation",
    # --- Education (expanded) ---
    "flashcards",
    "study-guide",
    "curriculum",
    "activity-book",
    "workbook",
    # --- Personal / Lifestyle ---
    "journal",
    "recipe-book",
    "personal-portfolio",
    "family-tree",
    # --- Media / Content ---
    "podcast-script",
    "video-script",
    "advertising-copy",
    # --- Religious / Spiritual ---
    "sermon",
    "liturgy",
]

ALL_EXAMPLE_NAMES = [
    "accessibility-test",
    "activity-book",
    "advanced-article",
    "advanced-beamer",
    "advanced-bibliography",
    "advanced-math",
    "advanced-report",
    "advanced-tables",
    "advanced-thesis",
    "advanced-tikz",
    "advertising-copy",
    "affidavit",
    "annotated-bibliography",
    "annual-report",
    "api-reference",
    "architecture-document",
    "art-catalogue",
    "article",
    "article-bengali",
    "article-chinese-traditional",
    "article-color",
    "article-czech",
    "article-danish",
    "article-dutch",
    "article-finnish",
    "article-french",
    "article-german-formal",
    "article-greek",
    "article-hindi",
    "article-italian",
    "article-norwegian",
    "article-polish",
    "article-portuguese",
    "article-russian",
    "article-spanish",
    "article-swedish",
    "article-thai",
    "article-turkish",
    "article-ukrainian",
    "article-vietnamese",
    "beamer-academic",
    "beamer-corporate",
    "beamer-defense",
    "beamer-minimal",
    "beamer-native",
    "bilingual-thesis",
    "blog-post",
    "book",
    "book-chapter",
    "brochure",
    "business-letter",
    "business-plan",
    "case-study",
    "changelog",
    "citation-styles",
    "cjk-chinese",
    "cjk-japanese",
    "cjk-korean",
    "clinical-report",
    "coding-standards",
    "color-themes",
    "comic-book",
    "compliance-document",
    "conference-paper",
    "contract",
    "course-material",
    "course-notes",
    "cover-letter",
    "cover-letter-formal",
    "curriculum",
    "cv",
    "cv-twopage",
    "data-sheet",
    "deployment-guide",
    "design-document",
    "developer-guide",
    "dictionary",
    "dissertation",
    "dissertation-proposal",
    "employee-handbook",
    "exam",
    "experiment-log",
    "family-tree",
    "financial-report",
    "flashcards",
    "grant-proposal",
    "handout",
    "homework",
    "ieee-paper",
    "inline-paper",
    "invitation",
    "invoice",
    "journal",
    "lab-report",
    "lecture-notes",
    "legal-brief",
    "legislation",
    "lesson-plan",
    "letter",
    "literature-review",
    "liturgy",
    "lua-showcase",
    "manual",
    "market-analysis",
    "meeting-minutes",
    "memo",
    "meta-analysis",
    "minimal-custom",
    "minimal-starter",
    "multi-language",
    "music",
    "newsletter",
    "novel",
    "onboarding-guide",
    "operations-manual",
    "audit-report",
    "data-dictionary",
    "feasibility-study",
    "greeting-card",
    "impact-report",
    "public-comment",
    "wedding-invitation",
    "workbook",
    "patent",
    "performance-review",
    "personal-portfolio",
    "plugin-demo",
    "podcast-script",
    "poetry-collection",
    "policy-document",
    "postdoc-report",
    "poster",
    "preprint",
    "presentation",
    "press-release",
    "privacy-policy",
    "proceedings",
    "product-spec",
    "program",
    "project-charter",
    "quarterly-report",
    "quiz",
    "recipe",
    "recipe-book",
    "regulation",
    "research-notebook",
    "research-proposal",
    "review-article",
    "risk-assessment",
    "rtl-arabic",
    "rtl-hebrew",
    "screenplay",
    "sermon",
    "short-story",
    "software-documentation",
    "stakeholder-report",
    "standard",
    "strategic-plan",
    "study-guide",
    "survey-report",
    "syllabus",
    "system-design",
    "technical-report",
    "technical-spec",
    "terms-of-service",
    "test-plan",
    "textbook",
    "thesis",
    "thesis-aalto",
    "thesis-cambridge",
    "thesis-chalmers",
    "thesis-chinese",
    "thesis-cmu",
    "thesis-columbia",
    "thesis-epfl",
    "thesis-eth",
    "thesis-harvard",
    "thesis-imperial",
    "thesis-japanese",
    "thesis-kit",
    "thesis-mit",
    "thesis-ntnu",
    "thesis-oxford",
    "thesis-princeton",
    "thesis-proposal",
    "thesis-spacing",
    "thesis-stanford",
    "thesis-tudelft",
    "thesis-tuhh",
    "thesis-tum",
    "thesis-uoft",
    "thesis-yale",
    "travel-guide",
    "troubleshooting-guide",
    "user-guide",
    "video-script",
    "white-paper",
    "working-paper",
    "zine",
]

DOCTYPE_TO_CLASS = {
    # scrbook types
    "thesis": "scrbook",
    "dissertation": "scrbook",
    "book": "scrbook",
    "dictionary": "scrbook",
    "proceedings": "scrbook",
    "textbook": "scrbook",
    "employee-handbook": "scrbook",
    "novel": "scrbook",
    "art-catalogue": "scrbook",
    "photo-book": "scrbook",
    "travel-guide": "scrbook",
    "recipe-book": "scrbook",
    "personal-portfolio": "scrbook",
    "activity-book": "scrbook",
    "workbook": "scrbook",
    # scrartcl types
    "article": "scrartcl",
    "journal": "scrartcl",
    "inlinepaper": "scrartcl",
    "cv": "scrartcl",
    "cover-letter": "scrartcl",
    "poster": "scrartcl",
    "presentation": "scrartcl",
    "letter": "scrartcl",
    "homework": "scrartcl",
    "exam": "scrartcl",
    "lecture-notes": "scrartcl",
    "syllabus": "scrartcl",
    "handout": "scrartcl",
    "memo": "scrartcl",
    "white-paper": "scrartcl",
    "invoice": "scrartcl",
    "recipe": "scrartcl",
    "blog-post": "scrartcl",
    "newsletter": "scrartcl",
    "brochure": "scrartcl",
    "invitation": "scrartcl",
    "program": "scrartcl",
    "changelog": "scrartcl",
    "grant-proposal": "scrartcl",
    "ieee": "scrartcl",
    "book-chapter": "scrartcl",
    "lab-report": "scrartcl",
    "literature-review": "scrartcl",
    "annotated-bibliography": "scrartcl",
    "preprint": "scrartcl",
    "working-paper": "scrartcl",
    "business-letter": "scrartcl",
    "meeting-minutes": "scrartcl",
    "case-study": "scrartcl",
    "quiz": "scrartcl",
    "lesson-plan": "scrartcl",
    "course-notes": "scrartcl",
    # Expanded academic
    "conference-paper": "scrartcl",
    "meta-analysis": "scrartcl",
    "research-notebook": "scrartcl",
    "experiment-log": "scrartcl",
    "survey-report": "scrartcl",
    "review-article": "scrartcl",
    "data-sheet": "scrartcl",
    # Expanded business
    "performance-review": "scrartcl",
    "project-charter": "scrartcl",
    "pitch-deck": "scrartcl",
    "press-release": "scrartcl",
    # Expanded creative
    "short-story": "scrartcl",
    "poetry-collection": "scrartcl",
    "screenplay": "scrartcl",
    "comic-book": "scrartcl",
    "zine": "scrartcl",
    "greeting-card": "scrartcl",
    "wedding-invitation": "scrartcl",
    "journal": "scrartcl",
    # Expanded education
    "flashcards": "scrartcl",
    "study-guide": "scrartcl",
    # Expanded legal
    "legal-brief": "scrartcl",
    "court-filing": "scrartcl",
    "affidavit": "scrartcl",
    "public-comment": "scrartcl",
    # Media/Content
    "podcast-script": "scrartcl",
    "video-script": "scrartcl",
    "advertising-copy": "scrartcl",
    # Religious
    "sermon": "scrartcl",
    # beamer
    "beamer": "beamer",
    # scrreprt types
    "manual": "scrreprt",
    "technicalreport": "scrreprt",
    "standard": "scrreprt",
    "patent": "scrreprt",
    "research-proposal": "scrreprt",
    "thesis-proposal": "scrreprt",
    "quarterly-report": "scrreprt",
    "strategic-plan": "scrreprt",
    "product-spec": "scrreprt",
    "course-material": "scrreprt",
    "software-documentation": "scrreprt",
    "api-reference": "scrreprt",
    "technical-spec": "scrreprt",
    "legislation": "scrreprt",
    "regulation": "scrreprt",
    "annual-report": "scrreprt",
    # Expanded scrreprt
    "clinical-report": "scrreprt",
    "dissertation-proposal": "scrreprt",
    "postdoc-report": "scrreprt",
    "business-plan": "scrreprt",
    "market-analysis": "scrreprt",
    "financial-report": "scrreprt",
    "onboarding-guide": "scrreprt",
    "risk-assessment": "scrreprt",
    "stakeholder-report": "scrreprt",
    "media-kit": "scrreprt",
    "user-guide": "scrreprt",
    "developer-guide": "scrreprt",
    "operations-manual": "scrbook",
    "architecture-document": "scrreprt",
    "design-document": "scrreprt",
    "test-plan": "scrreprt",
    "deployment-guide": "scrreprt",
    "troubleshooting-guide": "scrreprt",
    "coding-standards": "scrreprt",
    "data-dictionary": "scrreprt",
    "system-design": "scrreprt",
    "contract": "scrreprt",
    "terms-of-service": "scrreprt",
    "privacy-policy": "scrreprt",
    "compliance-document": "scrreprt",
    "policy-document": "scrreprt",
    "impact-report": "scrreprt",
    "audit-report": "scrreprt",
    "feasibility-study": "scrreprt",
    "curriculum": "scrreprt",
    "liturgy": "scrreprt",
    "family-tree": "scrartcl",
}

# Aliases that map example names to canonical doctypes
# (examples whose directory name differs from their doctype option)
DOCTYPE_ALIASES = {
    "technical-report": "technicalreport",
    "inline-paper": "inlinepaper",
    "cover-letter-formal": "cover-letter",
    "cv-twopage": "cv",
    "thesis-spacing": "thesis",
    "thesis-tuhh": "thesis",
    "article-color": "article",
    "citation-styles": "article",
    "multi-language": "article",
    "cjk-chinese": "article",
    "cjk-japanese": "article",
    "cjk-korean": "article",
    "rtl-arabic": "article",
    "rtl-hebrew": "article",
    "color-themes": "article",
    "lua-showcase": "article",
    "accessibility-test": "article",
    "minimal-custom": None,  # no doctype
    "minimal-starter": None,  # no doctype
    "beamer-academic": "presentation",
    "beamer-corporate": "presentation",
    "beamer-minimal": "presentation",
    "beamer-defense": "presentation",
    "beamer-native": "beamer",
    "article-bengali": "article",
    "article-chinese-traditional": "article",
    "article-czech": "article",
    "article-danish": "article",
    "article-dutch": "article",
    "article-finnish": "article",
    "article-french": "article",
    "article-german-formal": "article",
    "article-greek": "article",
    "article-hindi": "article",
    "article-italian": "article",
    "article-norwegian": "article",
    "article-polish": "article",
    "article-portuguese": "article",
    "article-russian": "article",
    "article-spanish": "article",
    "article-swedish": "article",
    "article-thai": "article",
    "article-turkish": "article",
    "article-ukrainian": "article",
    "article-vietnamese": "article",
    "thesis-aalto": "thesis",
    "thesis-cambridge": "thesis",
    "thesis-chalmers": "thesis",
    "thesis-chinese": "thesis",
    "thesis-cmu": "thesis",
    "thesis-columbia": "thesis",
    "thesis-epfl": "thesis",
    "thesis-eth": "thesis",
    "thesis-harvard": "thesis",
    "thesis-imperial": "thesis",
    "thesis-japanese": "thesis",
    "thesis-kit": "thesis",
    "thesis-mit": "thesis",
    "thesis-ntnu": "thesis",
    "thesis-oxford": "thesis",
    "thesis-princeton": "thesis",
    "thesis-stanford": "thesis",
    "thesis-tudelft": "thesis",
    "thesis-tum": "thesis",
    "thesis-uoft": "thesis",
    "thesis-yale": "thesis",
    # New examples with different dir names vs doctypes
    "ieee-paper": "ieee",
    "technical-spec": "technical-spec",
    # Advanced examples using existing doctypes
    "advanced-thesis": "thesis",
    "advanced-article": "article",
    "advanced-beamer": "beamer",
    "advanced-report": "technicalreport",
    "advanced-bibliography": "article",
    "advanced-math": "article",
    "advanced-tables": "article",
    "advanced-tikz": "article",
    "bilingual-thesis": "thesis",
    # New expanded examples
    "coding-standards": "standard",
    "architecture-document": "technicalreport",
    "design-document": "technicalreport",
    "system-design": "technicalreport",
    "test-plan": "technicalreport",
    "troubleshooting-guide": "manual",
    "deployment-guide": "manual",
    "developer-guide": "manual",
    "operations-manual": "manual",
    "user-guide": "manual",
    "family-tree": "article",
    "activity-book": "textbook",
    "workbook": "textbook",
}
