"""Scaffold commands mixin.

Provides commands for scaffolding new institutions and languages.
"""

from __future__ import annotations

import re
import shutil

import buildlib.config as _cfg


class ScaffoldMixin:
    """Mixin providing scaffold commands.

    Requires self.ui, self.runner to be set by the inheriting class.
    """

    def cmd_scaffold_institution(self, files: list[str]):
        """Create a new institution config from the generic template."""
        self.ui.header("Scaffold Institution")

        if not files:
            self.ui.warning("Usage: build.py scaffold-institution <name>")
            self.ui.info(
                "Creates config/institutions/<name>/<name>.sty from the generic template."
            )
            return

        name = files[0]
        if not re.match(r"^[a-zA-Z0-9_-]+$", name):
            self.ui.error(
                f"Invalid institution name '{name}'. "
                "Use only alphanumeric characters, hyphens, and underscores."
            )
            return
        repo_root = _cfg.REPO_ROOT
        src = repo_root / "config" / "institutions" / "generic"
        dst = repo_root / "config" / "institutions" / name

        if not dst.resolve().is_relative_to(repo_root / "config" / "institutions"):
            self.ui.error(
                f"Institution name '{name}' resolves outside institutions directory"
            )
            return

        if not src.exists():
            self.ui.error(f"Generic template not found at {src}")
            return

        if dst.exists():
            self.ui.error(f"Institution '{name}' already exists at {dst}")
            return

        shutil.copytree(src, dst)

        old_sty = dst / "generic.sty"
        new_sty = dst / f"{name}.sty"
        if old_sty.exists():
            old_sty.rename(new_sty)

        old_logo_dir = dst / "assets" / "logos" / "generic"
        new_logo_dir = dst / "assets" / "logos" / name
        if old_logo_dir.exists():
            old_logo_dir.rename(new_logo_dir)

        if new_sty.exists():
            content = new_sty.read_text(encoding="utf-8")
            content = content.replace(
                "config/institutions/generic/generic",
                f"config/institutions/{name}/{name}",
            )
            content = content.replace(
                "Generic Institution Configuration", f"{name} Institution Configuration"
            )
            content = content.replace("assets/logos/generic", f"assets/logos/{name}")
            content = content.replace("institution=generic]", f"institution={name}]")
            new_sty.write_text(content, encoding="utf-8")

        self.ui.success(f"Scaffolded institution: {name}")
        self.ui.info(f"  Config: {dst / f'{name}.sty'}")
        self.ui.info(f"  Assets: {dst / 'assets' / 'logos' / name}")
        self.ui.info("  Next: customize the .sty file, add your logo, update colors")
        self.ui.info(
            f"  Usage: \\documentclass[doctype=thesis,institution={name}]{{omnilatex}}"
        )

    def cmd_scaffold_language(self, files: list[str]):
        """Create a language addition guide with translation stubs."""
        self.ui.header("Scaffold Language")

        if not files:
            self.ui.warning("Usage: build.py scaffold-language <language-name>")
            self.ui.info(
                "Creates a guide file with translation stubs for adding a new language."
            )
            return

        lang = files[0].lower().strip()
        repo_root = _cfg.REPO_ROOT
        i18n_file = repo_root / "lib" / "language" / "omnilatex-i18n.sty"

        if not i18n_file.exists():
            self.ui.error(f"i18n module not found at {i18n_file}")
            return

        content = i18n_file.read_text(encoding="utf-8")
        keys = sorted(
            set(
                re.findall(
                    r"\\DeclareTranslation\{(?:english|german|french|spanish)\}\{(\w+)\}",
                    content,
                )
            )
        )

        if not keys:
            self.ui.error("No translation keys found in i18n module")
            return

        escaped_lang = re.escape(lang)
        if re.search(r"\\DeclareTranslation\{" + escaped_lang + r"\}", content):
            self.ui.warning(
                f"Language '{lang}' already has translations in the i18n module"
            )
            self.ui.info("Proceeding anyway to generate a fresh guide.")

        guide_path = repo_root / "docs" / f"language-guide-{lang}.tex"
        lines = [
            f"% Language addition guide for: {lang}",
            f"% Generated by build.py scaffold-language {lang}",
            "",
            "% Copy these translations into lib/language/omnilatex-i18n.sty",
            "% inside the \\AddBabelLanguage block.",
            "",
        ]
        for key in keys:
            lines.append(f"\\DeclareTranslation{{{lang}}}{{{key}}}%")
            lines.append(f"  % TODO: translate '{key}' to {lang}")
            lines.append("")

        guide_path.parent.mkdir(parents=True, exist_ok=True)
        guide_path.write_text("\n".join(lines), encoding="utf-8")

        self.ui.success(f"Language guide created: {guide_path}")
        self.ui.info(f"  Keys found: {len(keys)}")
        self.ui.info("  Next: fill in translations and add to omnilatex-i18n.sty")
