-- OmniLaTeX Formal Verification Proofs
-- Root library file — imports all proof modules

import OmniLaTeXProofs.BuildModes
import OmniLaTeXProofs.BuildModeStrictness
import OmniLaTeXProofs.BuildSystem
import OmniLaTeXProofs.DoctypeClassMapping
import OmniLaTeXProofs.DocumentSettings
import OmniLaTeXProofs.DoctypeResolution
import OmniLaTeXProofs.FloatInvariant
import OmniLaTeXProofs.FontHierarchy
import OmniLaTeXProofs.I18nCompleteness
import OmniLaTeXProofs.LanguageFallback
import OmniLaTeXProofs.ModuleIntegrity
import OmniLaTeXProofs.PageGeometry
import OmniLaTeXProofs.DoctypePageGeometry
import OmniLaTeXProofs.SecondaryLanguageCompleteness
import OmniLaTeXProofs.CrossReferenceConsistency
